import pandas as pd

# Carregar o arquivo CSV
df = pd.read_csv('arquivos não tratados/lojas.csv')

# Criar o dicionário de mapeamento de cidades para país
mapa_cidades = {
    'Berlim': 'Alemanha',
    'Johannesburg': 'África do Sul',
    'Tóquio': 'Japão',
    'Nairobi': 'Quênia',
    'Cingapura': 'Cingapura',
    'Kuala Lumpur': 'Malásia',
    'Buenos Aires': 'Argentina',
    'Katmandu': 'Nepal',
    'Kinshasa': 'República Democrática do Congo',
    'Sydney': 'Austrália',
    'São Paulo': 'Brasil',
    'Paris': 'França',
    'Colombo': 'Sri Lanka',
    'Bangkok': 'Tailândia',
    'Seul': 'Coreia do Sul',
    'Nova Deli': 'Índia',
    'Hong Kong': 'China',
    'Pequim': 'China',
    'Rio de Janeiro': 'Brasil',
    'Dubai': 'Emirados Árabes Unidos',
    'Londres': 'Reino Unido',
    'Moscou': 'Rússia',
    'Mumbai': 'Índia',
    'Jacarta': 'Indonésia',
    'Teerã': 'Irã',
    'Amã': 'Jordânia',
    'Lima': 'Peru',
    'Roma': 'Itália',
    'Cidade do México': 'México',
    'Madri': 'Espanha',
    'Riyadh': 'Arábia Saudita',
    'Cabul': 'Afeganistão',
    'Damasco': 'Síria',
    'Yangon': 'Mianmar',
    'Argel': 'Argélia',
    'Manila': 'Filipinas',
    'Islamabad': 'Paquistão',
    'Hanói': 'Vietnã',
    'Taipei': 'Taiwan',
    'Beirute': 'Líbano',
    'Bagdá': 'Iraque',
    'Santiago': 'Chile',
    'Casablanca': 'Marrocos',
    'Doha': 'Qatar',
    'Trípoli': 'Líbia',
    'Dhaka': 'Bangladesh',
    'Abu Dhabi': 'Emirados Árabes Unidos',
    'Dakar': 'Senegal',
    'Phnom Penh': 'Camboja',
    'Kyoto': 'Japão',
    'Yangon': 'Mianmar',
    'Argel': 'Argélia',
    'Manila': 'Filipinas',
    'Islamabad': 'Paquistão',
    'Hanói': 'Vietnã',
    'Taipei': 'Taiwan',
    'Beirute': 'Líbano',
    'Bagdá': 'Iraque',
    'Santiago': 'Chile',
    'Casablanca': 'Marrocos',
    'Doha': 'Qatar',
    'Trípoli': 'Líbia',
    'Dhaka': 'Bangladesh',
    'Abu Dhabi': 'Emirados Árabes Unidos',
    'Dakar': 'Senegal',
    'Phnom Penh': 'Camboja',
    'Cairo':  'Egito',
    'Jerusalém': 'Israel',
    'Berlim': 'Alemanha',
    'Johannesburg': 'África do Sul',
    'Tóquio': 'Japão',
    'Nairobi': 'Quênia',
    'Cingapura': 'Singapura',
    'Kuala Lumpur': 'Malásia',
    'Buenos Aires': 'Argentina',
    'Katmandu': 'Nepal',
    'Kinshasa': 'República Democrática do Congo',
    'Sydney': 'Austrália',
    'Toronto': 'Canadá',
    'Jacarta': 'Indonésia',
    'São Paulo': 'Brasil',
    'Dakar': 'Senegal',
    'Osaka': 'Japão',
    'Paris': 'França',
    'Colombo': 'Sri Lanka',
    'Bangkok': 'Tailândia',
    'Seul': 'Coreia do Sul',
    'Nova Deli': 'Índia',
    'Hong Kong': 'Hong Kong',
    'Beirute': 'Líbano',
    'Doha': 'Catar',
    'Hanói': 'Vietnã',
    'Damasco': 'Síria',
    'Taipei': 'Taiwan',
    'Abu Dhabi': 'Emirados Árabes Unidos',
    'Pequim': 'China',
    'Cabul': 'Afeganistão',
    'Bogotá': 'Colômbia',
    'Santiago': 'Chile',
    'Islamabad': 'Paquistão',
    'Bagdá': 'Iraque',
    'Lagos': 'Nigéria',
    'Manila': 'Filipinas',
    'Madri': 'Espanha',
    'Riyadh': 'Arábia Saudita',
    'Casablanca': 'Marrocos',
    'Dhaka': 'Bangladesh',
    'Trípoli': 'Líbia',
    'Phnom Penh': 'Camboja',
    'Rio de Janeiro': 'Brasil',
    'Yangon': 'Mianmar',
    'Jerusalém': 'Israel',
    'Argel': 'Argélia',
    'Túnis': 'Tunísia',
    'Roma': 'Itália',
    'Cidade do México': 'México',
    'Lima': 'Peru',
    'Nova York': 'Estados Unidos',
    'Dubai': 'Emirados Árabes Unidos',
    'Amã': 'Jordânia',
    'Londres': 'Reino Unido',
    'Mumbai': 'Índia',
    'Kyoto': 'Japão',
    'Cairo': 'Egito',
    'Teerã': 'Irã',
    'Los Angeles': 'Estados Unidos',
    'Moscou': 'Rússia',
    'Istambul': 'Turquia'
    # Adicione mais cidades conforme necessário
}

# Função para corrigir o país com base na cidade
def corrigir_pais(cidade):
    return mapa_cidades.get(cidade, 'Desconhecido')

# Aplicar a função para corrigir a coluna 'Pais'
df['Pais'] = df['Cidade'].apply(corrigir_pais)

# Excluir a coluna 'Regiao'
df = df.drop(columns=['Regiao'])

# Salvar o DataFrame corrigido em um novo arquivo CSV
df.to_csv('lojas_corrigidas.csv', index=False)
